REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

ACTION_QUEUE = "action_queue"
OBJECT_QUEUE = "object_queue"
POSE_QUEUE = "pose_queue"

SERVER_SLEEP = 0.25
CLIENT_SLEEP = 0.25
BATCH_SIZE = 4

IMAGE_WIDTH = 224
IMAGE_HEIGHT = 224
IMAGE_CHANS = 3
TIME_LENGTH = 10